version: '3.9'
services:
  library_ms_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 4300:8000
    depends_on:
      - mysql
    container_name: lbu_library_ms_api
  
  mysql:  
    image: mysql:8.0
    ports:
        - 3306:3306
    environment:
        - MYSQL_DATABASE=library_ms
        # - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
    volumes:
        - ./storage/dbdata:/var/lib/mysql

  # mysql:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #   - MYSQL_DATABASE=library_ms
  #   - MYSQL_USER=root
  #   - MYSQL_PASSWORD=root
  #   - MYSQL_ROOT_PASSWORD=root
  #   ports:
  #     - "3306:3306"
  #   container_name: mysql
  #   restart: unless-stopped
    
  #   # environment:
  #   #   - MYSQL_DATABASE=library_ms
  #   #   - MYSQL_USER=root
  #   #   - MYSQL_ROOT=root
  #   #   - MYSQL_PASSWORD=root
  #   #   - MYSQL_ROOT_PASSWORD=root
  #   volumes:
  #     - ./storage/dbdata:/var/lib/mysql
  